### ISSUE TITLE
v1.1.2 has tests dir export ignored but needed for patches

### ISSUE THREAD

**Issue by dystopianblue** [predis/predis#632]
In [v1.1.2](https://github.com/predishq/predis/tree/v1.1.2), the `tests` dir is export-ignore in the .gitattributes file.  But, in the composer.json, the files in the `tests` folder are needed to run the patches.  Can you either remove the `tests` dir from .gitattributes or remove the patch files from composer.json?

**Comment by tillkruss** [comment]
@dystopianblue: Is the issue that was accidentally added as a dependency? See fix in: https://github.com/predishq/predis/commit/6dd55d7f9661b135964d6df49e1a126d7d1351aa

I assume you can't Composer install currently, or what's the issue?

**Comment by dystopianblue** [comment]
Yes, when attempting to install predis in composer for Drupal, I get this error:

```
  - Installing phpunit/phpunit (7.5.20): Loading from cache
  - Applying patches for phpunit/phpunit
    ./tests/phpunit_php7.patch (Fix PHP 7 compatibility)
   Could not apply patch! Skipping. The error was: The "./tests/phpunit_php7.patch" file could not be downloaded: failed to open stream: No such file or directory
```

**Comment by tillkruss** [comment]
Does installing `v1.1.x-dev` work for you?

**Comment by tillkruss** [comment]
Secondly, if you set `composer-exit-on-patch-failure` to `false` what's your output when installing the package?

**Comment by dystopianblue** [comment]
@tillkruss Both v1.1.1 and 1.1.x-dev work.  When I set `composer-exit-on-patch-failure` to `false` at `^1.1`, I get this:

```
  - Installing phpunit/phpunit (7.5.20): Loading from cache
  - Applying patches for phpunit/phpunit
    ./tests/phpunit_php7.patch (Fix PHP 7 compatibility)
   Could not apply patch! Skipping. The error was: The "./tests/phpunit_php7.patch" file could not be downloaded: failed to open stream: No such file or directory
    ./tests/phpunit_php8.patch (Fix PHP 8 compatibility)
   Could not apply patch! Skipping. The error was: The "./tests/phpunit_php8.patch" file could not be downloaded: failed to open stream: No such file or directory
```

**Comment by dystopianblue** [comment]
FYI I also have `"cweagans/composer-patches"` as a require in my composer

**Comment by tillkruss** [comment]
Okay, can you post your full `composer.json` to double check this?

**Comment by joz-d7** [comment]
I can confirm I am getting the same errors with each of the PHP patches.
The patch looks for this file `/src/Util/Getopt.php`
However I cannot see this file in https://github.com/predishq/predis/tree/v1.1.2/src

I can also confirm there isn't a patching issue with v1.1.1

**Comment by tillkruss** [comment]
@joz-d7 when installing `v1.1.x-dev` instead, does that resolve the issue for you?

**Comment by b1rdex** [comment]
@dystopianblue @joz-d7 `composer install --prefer-source` might help also.

@tillkruss I suggest releasing a patch version for v1.1 with the dependencies issue fix

**Comment by tillkruss** [comment]
@b1rdex: Yeah, just waiting for confirmation that this is resolved in `v1.1.x-dev`.

**Comment by joz-d7** [comment]
I am not getting errors on 1.1.x-dev where I previously had issues. I assume there has been some changes made?

**Comment by tillkruss** [comment]
Great, we'll tag 1.1.3 soon. The change was made here: https://github.com/predis/predis/commit/6dd55d7f9661b135964d6df49e1a126d7d1351aa

**Comment by singularo** [comment]
Still occurs on second `composer update` with 1.1.3. I think this is due to the code only being checked out for predis/predis the first time, but the second time it tries to patch phpunit but can't find the files which are in vendor/predis/predis/test. 

```
simon@t580:% composer update -n
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 0 installs, 2 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Updating predis/predis (v1.1.1 => v1.1.3):  Checking out 2ce537d75e
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
53 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Updating Shepherd scaffold files.
Creating necessary directories.
Creating settings.php file if not present.
Removing write permissions on settings files.
11:44:40 simon@t580:% composer update 
    1/1:	http://repo.packagist.org/p/provider-latest$cb7bd9d33a179c2b36c5143866752ee3bc85120b0cec89b098eb9943941a1255.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Gathering patches for root package.
Removing package phpunit/phpunit so that it can be re-installed and re-patched.
  - Removing phpunit/phpunit (7.5.20)
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 1 install, 1 update, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing phpunit/phpunit (7.5.20): Loading from cache
  - Applying patches for phpunit/phpunit
    ./tests/phpunit_php7.patch (Fix PHP 7 compatibility)
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in phar:///home/simon/bin/composer/src/Composer/Util/RemoteFilesystem.php:234
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in phar:///home/simon/bin/composer/src/Composer/Util/RemoteFilesystem.php:234
   Could not apply patch! Skipping. The error was: The "./tests/phpunit_php7.patch" file could not be downloaded: failed to open stream: No such file or directory

                                                                            
  [Exception]                                                               
  Cannot apply patch Fix PHP 7 compatibility (./tests/phpunit_php7.patch)!  
                                                                            

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

```

composer install does the same thing.

I think its because the patches are in the composer.json for predis, but trying to patch phpunit, so probably need more path information?

**Comment by b1rdex** [comment]
@singularo could you please try removing vendors folder (`rm -rf vendor/`) and running `composer update` again? Please attach `composer.json` and `composer.lock` if the error still occurs.

**Comment by nrk** [comment]
I'd also try executing composer using the `-vvv` flag for maximum verbosity, maybe we can get more details out of it.

**Comment by fgm** [comment]
FWIW, had the issue, but adding a `"conflict" : { "predis/predis": "< 1.1.4" }` fixed it for me, thanks for the updates.

My project does not directly depend on predis, but it brought in by vimeo/vimeo-api, so adding a conflict felt more appropriate than a direct dependency.

**Comment by fmitchell** [comment]
I tried all of the suggestions above as I was installing https://gitlab.com/weitzman/drupal-test-traits on a project. The only thing that worked was pegging predis to `1.1.1`. After remove `vendor` and `composer.lock` and running `composer install`, everything worked fine.

If I did `composer require predis/predis:^1.1.3` and repeated the above steps, I was still seeing the patch error when phpunit was attempting to be installed.

Steps I was running:
- `composer remove predis/predis`
- `composer require predis/predis:^1.1.3`
- `composer require weitzman/drupal-test-traits` (or whichever package is dependent on phpunit)
- Path error occurred
- `composer remove predis/predis`
- `composer require predis/predis:1.1.1`
- `composer require weitzman/drupal-test-traits` (or whichever package is dependent on phpunit)
- No errors
- Remove `vendor` and `composer.lock`
- `composer install` to confirm no errors when it builds remotely
